version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          command: |
            go get golang.org/x/tools/cmd/cover
            go get github.com/mattn/goveralls
      - run:
          command: |
            go test -covermode=count -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_REPO_TOKEN
            mv coverage.html /tmp/artifacts
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ANGAGO_IMAGE_NAME="manigandanjeff/angago"' >> $BASH_ENV
      - run:
          name: Build project
          command: |
            export CGO_ENABLED=0
            make GOOS=linux build-server
            docker build -t $ANGAGO_IMAGE_NAME:latest .
      - run:
          name: Save image to an archive
          command: |
            mkdir docker-image
            docker save -o docker-image/image.tar $FULL_IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - docker-image
  deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ANGAGO_IMAGE_NAME="manigandanjeff/angago"' >> $BASH_ENV
            echo 'export IMAGE_TAG_NAME="${CIRCLE_BRANCH}-$(date +%Y%m%d%H%M%S)"' >> $BASH_ENV
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker-image/image.tar
      - run:
          name: Push image to dockerhub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $ANGAGO_IMAGE_NAME:latest $ANGAGO_IMAGE_NAME:$IMAGE_TAG_NAME
            docker push $ANGAGO_IMAGE_NAME:latest
            docker push $ANGAGO_IMAGE_NAME:$IMAGE_TAG_NAME
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
