version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          command: |
            go get golang.org/x/tools/cmd/cover
            go get github.com/mattn/goveralls
      - run:
          command: |
            go test -covermode=count -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_REPO_TOKEN
            mv coverage.html /tmp/artifacts
      - codecov/upload:
          file:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go build
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts
